# Generated by Django 4.1.1 on 2022-10-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapTransporte',
            fields=[
                ('id_transporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('refrigeracion', models.BooleanField(default=False)),
                ('cap_carga', models.BigIntegerField()),
                ('cap_tamano', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cap_transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('n_ciudad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('n_estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.BigIntegerField(primary_key=True, serialize=False)),
                ('n_pais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigIntegerField(primary_key=True, serialize=False)),
                ('n_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('run', models.BigIntegerField()),
                ('usuario_activo', models.BooleanField(default=False)),
                ('superuser', models.BooleanField(default=False)),
                ('id_ciudad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
